# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 18:13
from __future__ import unicode_literals

import SilentD.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(default=' ', max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(blank=True, upload_to=SilentD.models.generate_path)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('Diagnostic', 'Diagnostic'), ('Research', 'Research'), ('Manager', 'Manager'), ('Quality', 'Quality'), ('Super', 'Super')], default='Diagnostic', max_length=100)),
                ('cfia_access', models.BooleanField(default=False)),
                ('lab', models.CharField(blank=True, choices=[(1, 'St-Johns'), (2, 'Dartmouth'), (3, 'Charlottetown'), (4, 'St-Hyacinthe'), (5, 'Longeuil'), (6, 'Fallowfield'), (7, 'Carling'), (8, 'Greater Toronto Area'), (9, 'Winnipeg'), (10, 'Saskatoon'), (11, 'Calgary'), (12, 'Lethbridge'), (13, 'Burnaby'), (14, 'Sidney'), (15, 'Other')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(default=' ', max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('num_files', models.IntegerField(default=0)),
                ('organism', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(blank=True, max_length=20)),
                ('genesippr_results', models.CharField(blank=True, max_length=50)),
                ('files', models.ManyToManyField(to='SilentD.Data')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(default=' ', max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('strain', models.CharField(blank=True, max_length=50)),
                ('genus', models.CharField(blank=True, max_length=50)),
                ('matches', models.CharField(blank=True, max_length=50)),
                ('runtype', models.CharField(blank=True, max_length=20)),
                ('project_id', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
